import type { Metadata } from "next";
import "./globals.css";
import TopButtons from "./components/shared/TopButtons";
import { SettingsProvider } from "./components/shared/SettingsContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <SettingsProvider>
          <main className="min-h-screen min-w-screen flex flex-col">
            {children}
            <TopButtons />
          </main>
        </SettingsProvider>
      </body>
    </html>
  );
}
